name: SLAMtestCoils
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - numpy=2.*
  - scipy>=1.14
  - matplotlib
  - pandas

  - pip:
      - jax==0.8.0
      - jaxlib==0.8.0
      - jaxellip==0.0.1
      - diffrax==0.7.0
      - equinox==0.13.2
      - lineax==0.0.8
      - optimistix==0.0.11
      - jaxtyping
      - opt_einsum